server {
    listen 80;
    client_max_body_size 500M;

    # MinIO 媒体文件代理
    location /minio-proxy/ {
        proxy_pass http://minio:9000/;
        proxy_set_header Host minio:9000;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # API 代理
    location / {
        proxy_pass http://app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
